[package]
name = "atlas"
version = "0.1.0"
authors = ["krissemicolon <krissemicolon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TUI
tui = "0.13"
termion = "1.5"
